# Generated by Django 5.2.15 on 2026-06-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('countries', models.JSONField(blank=True, default=list)),
                ('key_ports', models.JSONField(blank=True, default=list)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Market regions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'region'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('textiles', 'Textiles'), ('engineering', 'Engineering'), ('chemicals', 'Chemicals'), ('food-beverage', 'Food & beverage'), ('handicrafts', 'Handicrafts')], max_length=32)),
                ('hs_code', models.CharField(blank=True, max_length=64)),
                ('origins', models.JSONField(blank=True, default=list)),
                ('markets', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=list)),
                ('packaging', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('freight', 'Freight'), ('customs', 'Customs & regulatory'), ('documentation', 'Documentation'), ('warehousing', 'Warehousing'), ('trade-finance', 'Trade finance'), ('consulting', 'Consulting')], max_length=32)),
                ('icon', models.CharField(choices=[('ship', 'Ship'), ('plane', 'Plane'), ('shield', 'Shield'), ('file', 'File'), ('warehouse', 'Warehouse'), ('chart', 'Chart'), ('globe', 'Globe')], default='ship', max_length=32)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
