# Generated by Django 5.2.15 on 2026-06-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('countries', models.JSONField(blank=True, default=list)),
                ('key_ports', models.JSONField(blank=True, default=list)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Market regions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'region'],
            },
        ),
        migrations.CreateModel(
            name='ExportCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(help_text='e.g. Bangladesh, Dubai', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional context, e.g. UAE, South Asia', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('key_ports', models.JSONField(blank=True, default=list)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_countries', to='catalog.marketregion')),
            ],
            options={
                'verbose_name': 'Export country',
                'verbose_name_plural': 'Export countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('hs_code', models.CharField(blank=True, max_length=64)),
                ('origins', models.JSONField(blank=True, default=list)),
                ('markets', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=list)),
                ('packaging', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
