# Generated by Django 5.2.15 on 2026-06-17 10:06

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product photo shown on the website (JPEG, PNG, or WebP, max 5 MB).', null=True, upload_to=catalog.models.product_image_upload_to),
        ),
    ]
