# Generated by Django 5.2.15 on 2026-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, help_text='Customer tax registration (GSTIN, VAT, etc.), if applicable', max_length=20, verbose_name='GSTIN / tax ID'),
        ),
    ]
