# Generated by Django 5.2.15 on 2026-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_gstin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, help_text='Leave blank for overseas buyers. Use GSTIN, VAT, or TIN only when the customer has one.', max_length=20, verbose_name='Buyer tax ID (optional)'),
        ),
    ]
