# Generated by Django 5.2.15 on 2026-06-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Currency code'),
        ),
    ]
