# Generated by Django 5.2.15 on 2026-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_invoice_shipping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_gstin',
            field=models.CharField(blank=True, help_text='Buyer GSTIN or tax registration, if applicable', max_length=20, verbose_name='Customer GSTIN / tax ID'),
        ),
    ]
