# Generated by Django 5.2.15 on 2026-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_invoice_number_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportreport',
            name='report_type',
            field=models.CharField(choices=[('export_sales', 'Export sales & invoices'), ('inquiries_summary', 'Inquiry & lead summary'), ('pipeline', 'Sales pipeline & conversion'), ('leads_by_destination', 'Leads by export market'), ('customer_summary', 'Customers & buyers'), ('catalog', 'Catalog & markets overview')], max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_gstin',
            field=models.CharField(blank=True, help_text='Leave blank for export invoices to foreign buyers. Fill only for Indian GSTIN or a foreign VAT/TIN.', max_length=20, verbose_name='Buyer tax ID (optional)'),
        ),
    ]
